version: 1.0.{build}
platform:
  - x64

image: Visual Studio 2017

install:
  - cmd: echo "Downloading conan..."
  - cmd: set PATH=%PATH%;%PYTHON%/Scripts/
  - cmd: pip.exe install conan
  - cmd: conan user
  - cmd: conan remote add public-conan https://api.bintray.com/conan/bincrafters/public-conan
  - cmd: conan remote add public-jbl https://api.bintray.com/conan/jblort/public-jbl
  - cmd: conan --version

build_script:
  - cmd: mkdir build
  - cmd: cd build
  - cmd: conan install .. --build missing
  - cmd: cmake ../ -G "Visual Studio 15 2017 Win64"
  - cmd: cmake --build . --config Release

test_script:
  - cmd: cd bin
  - cmd: raytracerb.exe

branches:
  only:
    - master
