language: cpp

linux: &linux
  os: linux
  dist: trusty
  sudo: required
  compiler: gcc
  addons: &clang5
    apt:
      sources:
        - ubuntu-toolchain-r-test
      packages:
        - gcc-7
        - g++-7
    sonarcloud:
      organization: jblort-github
      token:
        secure: $SONAR_TOKEN


osx: &osx
  os: osx
  compiler: clang

matrix:
  include:

    # Linux C++14 GCC builds
    #- os: linux
    #  compiler: gcc
    #  addons: &gcc6
    #    apt:
    #      sources: ['ubuntu-toolchain-r-test']
    #      packages: ['g++-6']
    #  env: COMPILER='g++-6' BUILD_TYPE='Release'

    #- os: linux
    #  compiler: gcc
    #  addons: *gcc6
    #  env: COMPILER='g++-6' BUILD_TYPE='Debug'

    #Linux C++14 Clang builds
    - <<: *linux
      env: BUILD_TYPE='Debug' MATRIX_EVAL='CC=gcc-7 && CXX=g++-7' SONAR_SCAN=true

    - <<: *linux
      env: BUILD_TYPE='Debug' MATRIX_EVAL='CC=gcc-7 && CXX=g++-7' SONAR_SCAN=true

    # OSX C++14 Clang Builds

    - os: osx
      compiler: clang
      env: BUILD_TYPE='Debug' SONAR_SCAN=false


    - os: osx
      compiler: clang
      env: BUILD_TYPE='Release' SONAR_SCAN=false

before_install:
- eval "${MATRIX_EVAL}"

install:
# Install conan
- sudo pip install conan --upgrade --ignore-installed
# Add relevant conan repositories
- conan remote add public-conan https://api.bintray.com/conan/bincrafters/public-conan
- conan remote add public-jbl https://api.bintray.com/conan/jblort/public-jbl
# Automatic detection of your arch, compiler, etc.
- conan user
- conan user -p $CONAN_API_KEY -r public-jbl $CONAN_USER_NAME
# Install cmake
#- if [ $TRAVIS_OS_NAME = osx ]; then brew install cmake; fi

before_script:
- mkdir bw_output
- cd bw_output
- conan install .. --build missing
- cmake ..
- cd ..
- mkdir build
- cd build
- conan install .. --build missing
- cmake ..

script:
- cmake --build .
- ctest -V
- cd ..
- if [ "$SONAR_SCAN" = true ]; then build-wrapper-linux-x86-64 --out-dir bw_output cmake --build build; fi
- if [ "$SONAR_SCAN" = true ]; then sonar-scanner; fi

branches:
    only:
        - master

notifications:
    email: false
